document.addEventListener("DOMContentLoaded",()=>{const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const menuBtn=$("#menuBtn"),menu=$("#menuPanel");
function go(id){const el=$("#"+id);if(!el)return;menu.classList.remove("open");menuBtn.classList.remove("open");menuBtn.setAttribute("aria-expanded","false");document.body.classList.remove("no-scroll");el.scrollIntoView({behavior:window.matchMedia("(prefers-reduced-motion: reduce)").matches?"auto":"smooth",block:"start"})}
$$("[data-go]").forEach(b=>b.addEventListener("click",()=>go(b.dataset.go)));
menuBtn.addEventListener("click",()=>{const open=!menu.classList.contains("open");menu.classList.toggle("open",open);menuBtn.classList.toggle("open",open);menuBtn.setAttribute("aria-expanded",String(open));document.body.classList.toggle("no-scroll",open)});
const photos=[{src:"assets/casa.jpg",alt:"Sítio do Julinho"},{src:"assets/paisagem.jpg",alt:"Paisagem do Sítio do Julinho"}];let index=0;
const galleryImg=$("#galleryImage"), lightbox=$("#lightbox"),lightboxImg=$("#lightboxImage");
function setPhoto(i){index=(i+photos.length)%photos.length;galleryImg.src=photos[index].src;galleryImg.alt=photos[index].alt;$$(".thumb").forEach((x,n)=>x.classList.toggle("active",n===index))}
$$(".thumb").forEach(b=>b.addEventListener("click",()=>setPhoto(Number(b.dataset.index))));
$(".prev").addEventListener("click",()=>setPhoto(index-1));$(".next").addEventListener("click",()=>setPhoto(index+1));
$("#galleryMain").addEventListener("click",()=>{lightboxImg.src=photos[index].src;lightboxImg.alt=photos[index].alt;lightbox.classList.add("open");lightbox.setAttribute("aria-hidden","false");document.body.classList.add("no-scroll")});
function closeOverlay(el){el.classList.remove("open");el.setAttribute("aria-hidden","true");document.body.classList.remove("no-scroll")}
$("#lightboxClose").addEventListener("click",()=>closeOverlay(lightbox));lightbox.addEventListener("click",e=>{if(e.target===lightbox)closeOverlay(lightbox)});
const data={quartos:["Quartos","3 quartos para acomodar a estadia no sítio.","assets/casa.jpg"],lazer:["Piscina","A piscina faz parte da estrutura de lazer informada para o Sítio do Julinho.","assets/casa.jpg"],gourmet:["Área gourmet","Área gourmet com churrasqueira e fogão a lenha, conforme informações fornecidas.","assets/casa.jpg"],fogo:["Fogo de chão","Um espaço pensado para momentos ao ar livre, com fogo de chão.","assets/paisagem.jpg"],represa:["Represa do Peti","O sítio está às margens da Represa do Peti, um dos destaques da localização.","assets/paisagem.jpg"],estrutura:["Estrutura","3 banheiros e capacidade informada de até 15 pessoas.","assets/casa.jpg"]};
const pm=$("#placeModal");$$(".place-card").forEach(b=>b.addEventListener("click",()=>{const d=data[b.dataset.place];$("#placeTitle").textContent=d[0];$("#placeText").textContent=d[1];$("#placePhoto").src=d[2];$("#placePhoto").alt=d[0]+" — Sítio do Julinho";pm.classList.add("open");pm.setAttribute("aria-hidden","false");document.body.classList.add("no-scroll")}));
$("#placeClose").addEventListener("click",()=>closeOverlay(pm));pm.addEventListener("click",e=>{if(e.target===pm)closeOverlay(pm)});
document.addEventListener("keydown",e=>{if(e.key==="Escape"){if(lightbox.classList.contains("open"))closeOverlay(lightbox);if(pm.classList.contains("open"))closeOverlay(pm);if(menu.classList.contains("open")){menu.classList.remove("open");menuBtn.classList.remove("open");menuBtn.setAttribute("aria-expanded","false");document.body.classList.remove("no-scroll")}}});
let touchX=0;$(".gallery-main").addEventListener("touchstart",e=>touchX=e.changedTouches[0].screenX,{passive:true});$(".gallery-main").addEventListener("touchend",e=>{const dx=e.changedTouches[0].screenX-touchX;if(Math.abs(dx)>45)setPhoto(index+(dx<0?1:-1))},{passive:true});
});